mysite/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
    # /resources
    path('resources', views.resources, name='resources'),
    path('resourcesT', views.resourcesT, name='resources'),
    path('fileareport', views.questions, name='Info'),
    path('signin', views.emailver, name='Verify Email'),
    path('confidentiality', views.confidentiality, name='Conf'),
    path('case', views.case, name='What Happened'),
    path('attributes', views.attributecollection, name='Perpetrator Details'),
    path('match', views.match, name='Perpetrator Match'),
    path('login', views.login, name='Login'),
    path('match', views.match, name='Match')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

mysite/app/models.py
from django.db import models

# Create your models here.

class Report(models.Model):
    DEFAULT = 50
    id = models.IntegerField(primary_key=True)
    uwnetid = models.CharField(max_length = DEFAULT, null=True, default=None, blank=True)
    first_name = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    last_name = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    case_type = models.CharField(max_length=DEFAULT, null=True, default="None", blank=True)
    date = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    description = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    location = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    hair_color = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    eye_color = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    age = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    ethnicity = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    university = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    organization = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    ig_acc = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    fb_acc = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    phone_num = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)
    snap_acc = models.CharField(max_length=DEFAULT, null=True, default=None, blank=True)

    def __str__(self):
        return self.case_type

    def compare(this, other):
        return (this and other) and (this.casefold() == other.casefold())

    def checkMatch(self):
        allReports = Report.objects.all()
        matches = []
        for prev in allReports:
            if (compare(self.last_name, prev.last_name) and compare(self.first_name, prev.first_name)) or compare(
                    self.ig_acc, prev.ig_acc) or compare(self.phone_num, prev.phone_num):
                matches.append(prev)

        return len(matches)

    def checkMatchSimple(self):
        allReports = Report.objects.all()
        matches = []
        for prev in allReports:
            if ((self.last_name and prev.last_name) and (self.last_name.casefold() == prev.last_name.casefold())):
                matches.append(prev)

        return len(matches) - 1

    def id(self):
        return self.id

mysite/app/forms.py
from django import forms
from .models import Report

class loginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password')

class caseForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ["id", "case_type", "date", "description"]


class agreeToTermsForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ["id"]

mysite/app/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from .forms import caseForm, agreeToTermsForm
from .models import Report

def index(request):
    return render(request, 'app/index.html')


def mockIP():
    return 12356765435654


def getID(Report):
    return Report.id


def confidentiality(request):
    if request.POST:
        print("Begun reporting")
        return render(request, 'app/confidentiality.html')
    return render(request, 'app/confidentiality.html')


def case(request):
    initial = {'id': request.session.get('id', None)}
    form = agreeToTermsForm(request.POST or None, initial=initial)
    if request.method == 'POST':
        report = form.save(commit=False)
        report.save()
        print(report.id)
        print("collecting ip data for form")
        request.session['id'] = report.id
        return render(request, 'app/case.html')
    return render(request, 'app/case.html', {'form': form})


def attributecollection(request):
    id = request.session.get('id', None)
    report = Report.objects.filter(id=id)
    if request.method == 'POST':
        form = caseForm(request.POST or None)
        if form.is_valid():
            form.save()
            report.case_type=form["case_type"]
            report.date=form["date"]
            report.description=form["description"]
            print(report.description)
            return render(request, 'app/attrCol.html')
    return render(request, 'app/attrCol.html')


def resources(request):
    print("received to resources")
    return render(request, 'app/resources.html')


def resourcesT(request):
    print("Received request to resourcesT")
    reps = Report.objects.all()
    single = reps[len(reps) - 3]
    try:
        address = single.uwnetid + "@uw.edu"
        send_mail('Hi there, this email is to notify you of an update related to your SAVE report',
                  'Please visit http://127.0.0.1:8080/',
                  'save2019@hushmail.com',
                  [address],
                  fail_silently=False)
    except TypeError:
        pass

    return render(request, 'app/resources.html', {'submitted': 'TRUE'})


def questions(request):
    return render(request, 'app/question.html')


def emailver(request):
    return render(request, 'app/emailVer.html')

def login(request):
    return render(request, 'app/login.html')


def match(request):
    allReports = Report.objects.all()
    numMatches = 0
    if allReports.count() > 0:
        thisReport = allReports[len(allReports) - 1]
        numMatches = thisReport.checkMatchSimple()


    if (numMatches):
        return render(request, 'app/match.html', {'Matches':numMatches})
    else:
        return render(request, 'app/match.html')

mysite/app/templates/app/attrCol.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<!DOCTYPE html>
  <html>
    <head>
      <title>Attribute Collection</title>
      <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

    </head>
    <body id="class">
      <div class="testbox">
        <form action="/">
          <h1>Attribute Collection</h1>
          <p>You must input at least a first and last name in order for us to compare reports for the same perpetrator.</p>
          <h4>First Name:</h4>
            <textarea rows="1" class="text"></textarea>
          <h4>Last Name:</h4>
              <textarea rows="1" class="text"></textarea>
          <h4>Add Social Media Identifiers (Optional):</h4>
              <p><textarea rows="1" placeholder="Instagram Handle" class="text"></textarea></p>
              <p><textarea rows="1" placeholder="Facebook URL" class="text"></textarea></p>
              <p><textarea rows="1" placeholder="Snapchat Username" class="text"></textarea></p>
              <p><textarea rows="1" placeholder="Phone Number" class="text"></textarea></p>
            <br>
          <h3>Physical Characteristics:</h3>
          <h4>Gender:</h4>
          <select class="text">
            <option value=""></option>
            <option value="">Male</option>
            <option value="2">Female</option>
            <option value="3">Other</option>
          </select>
          <h4>Height:</h4>
          <select class="text">
            <option value="" ></option>
            <option value="">4'11"-</option>
            <option value="">5'0" - 5'2"</option>
            <option value="2">5'3"- 5'5"</option>
            <option value="3">5'6" - 5'8"</option>
            <option value="4">5'9" - 6'1"</option>
            <option value="5">6'2" - 6'4"</option>
            <option value="6">6'5" - 6"7</option>
            <option value="7">6'8" - 6'10"</option>
            <option value="">6'11" - 7'0"</option>
            <option value="8">7'1"+</option>
          </select>
          <h4>Eye Color:</h4>
          <select class="text">
            <option value=""></option>
            <option value="">Black</option>
            <option value="2">Green</option>
            <option value="3">Blue</option>
            <option value="4">Brown</option>
          </select>
          <h4>Hair Color:</h4>
          <select class="text">
            <option value=""></option>
            <option value="">Black</option>
            <option value="2">Brown</option>
            <option value="4">Light Brown</option>
            <option value="3">Blonde</option>
            <option value="4">Light Blonde</option>
          </select>
          <h4>Ethnicity:</h4>
          <select class="text">
            <option value=""></option>
            <option value="">American Indian or Alaskan Native</option>
            <option value="2">Asian or Pacific Islander</option>
            <option value="4">Black</option>
            <option value="3">White</option>
            <option value="4">Hispanic</option>
          </select>
          <form>
            <br><br>
            <!-- This is a decision -->
              <button type="submit" formaction="/match">Submit</button>
          </form>
        </form>
      </div>s
    </body>
  </html>

mysite/app/templates/app/base.html
{% load static %}

{% block content %}
<div class="w3-top">
  <div class="w3-bar w3-deep-purple w3-card w3-center-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-deep-purple" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
    <a href="/resources" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Resources</a>

  </div>
</div>
{% endblock %}

mysite/app/templates/app/case.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <title>General Information</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  </head>
  <body>
    <div class="testbox">
      <form action="/" method="post">
        {% csrf_token %}
        <h1>General information</h1>
        <h4>What type of sexual misconduct/assault?<span>*</span></h4>
        <select for="case_type">
          <option value="">--Select Type of Sexual Harassment--</option>
          <option value="">Staring/Leering</option>
          <option value="2">Comments/Gestures: Asking Personal Questions</option>
          <option value="3">Comments/Gestures: Comments about appearance</option>
          <option value="4">Comments/Gestures: Flirting</option>
          <option value="5">Comments/Gestures: Explicit Gestures or Comments</option>
          <option value="6">Indecent Photography Without Consent</option>
          <option value="7">Indecent Unsolicited Content</option>
          <option value="8">Verbal Threat of Sexual Assault</option>
          <option value="9">Attempted Non-Consensual Touching</option>
          <option value="10">Non-Consensual Touching</option>
          <option value="11">Attempted Non-Consensual Kissing</option>
          <option value="12">Non-Consensual Kissing</option>
          <option value="13">Attempted Non-Consensual Penetration</option>
          <option value="14">Non-Consensual Penetration</option>
        </select>
        <label>Date of Occurrence:</label>
        <input for="id_date" type="month" id="start" name="start"
       min="2000-01" value="YYYY-MM">
        <h4>Additional information</h4>
        <p class="small">Use this space to input any additional details.</p>
          <textarea for="id_description" rows="5" style="font-size: 14px;"></textarea>
        <div class="btn-block">
          <button type="submit" formaction="attributes" formmethod="post">Continue</button>
        </div>
      </form>
    </div>
  </body>
</html>

mysite/app/templates/app/confidentiality.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <title>Confidentiality Agreement</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  </head>
    <div class="testbox">
      <form action="/">
          {% csrf_token %}
        <h1>Confidentiality Agreement</h1>
          <br><br>
            <h4>All information that you submit in the report will be confidential.
                By agreeing to submit a report, you acknowledge that if another user
                submits a report with the same perpetrator, they (and you) will be
                notified that another case with their perpetrator exists. </h4>

            <h4>After agreeing, you will be directed to authenticate your identity with
                your UW Net ID. We do this in order to make sure the tool is not abused.</h4>
            <br><br>
            <head>
            <script>
              function activateButton(element) {
                  if(element.checked) {
                    document.getElementById("submit").disabled = false;
                   }
                   else  {
                    document.getElementById("submit").disabled = true;
                  }
              }
            </script>
            </head>

            <body>
             <input type="checkbox" name="terms" id="terms" onchange="activateButton(this)">  I Acknowledge the Confidentiality Agreement
            <br><br>
              <input type="submit" name="submit" id="submit" formaction="case" formmethod="post" disabled="true">
            </body>
      </form>
    </div>
  </body>
</html>

mysite/app/templates/app/emailVer.html
{% extends index.html %}


<!DOCTYPE html>
{% block main_body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>

{{ block.super }}
{% endblock main_body %}
</html>

mysite/app/templates/app/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>UW login account</title>
    <link href="login.css" rel="stylesheet">
  </head>
  <body>
    <section id="loginBox">
    	<h2><b>UW Net ID Authentication</b></h2>
    	<form method="post" class="minimal" action="/login/">
    		<label for="username">
    			UW Net ID:
    			<input type="text" name="username" id="username"  pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}$" required="required" />
    		</label><br>
    		<label for="password">
    			Password:
    			<input type="password" name="password" id="password"  pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
    		</label><br>
    		<button type="submit" class="btn-minimal">Authenticate</button>
    	</form>
    </section>
  <style>
  *{
		margin: 0;
		padding: 0;
		outline: none;

		-webkit-box-sizing: border-box;
  		-moz-box-sizing: border-box;
  		box-sizing: border-box;
	}

	body {
		background: #eee;
		background-color: rgb(127,0,255);
		color: #444;
		-webkit-font-smoothing: antialiased;
		font-family: "Open Sans", Arial, Helvetica, Geneva, sans-serif;
		font-size: 16px;
		font-weight: 400;
		height: auto !important;
		height: 100%;
		line-height: 1.6em;
		min-height: 100%;
	}

	h2 {
		color: rgb(34,34,34);
		font-size: 20px;
		font-weight: 200;
		margin: 0 0 24px 0;
	}

	/*BUTTON DESIGN*/
	[class*='btn-'] {
		border: none;
		border-bottom: 2px solid rgba(0,0,0,.15);
		border-top: 1px solid rgba(255,255,255,.15);
		border-radius: 3px;
		color: #fff;
		display: inline-block;
		font: -webkit-small-control;
		font-size: .7em;
		letter-spacing: 1px;
		line-height: 140%;
		padding: 10px 20px;
		text-decoration: none;
		text-shadow: 0 1px 1px rgba(0, 0, 0, 0.25);
		text-transform: uppercase;

		-webkit-transition: all 0.1s linear;
     	-moz-transition: all 0.1s linear;
       	-o-transition: all 0.1s linear;
          transition: all 0.1s linear;
	}

		.btn-minimal {
		background-color: rgb(255,255,255);
		border-radius: 0;
		border: 1px solid rgb( 186, 186, 186 );
		color: rgb( 186, 186, 186 );
		text-shadow: 0 1px 1px rgba(255, 255, 255, 1);
	}

		.btn-minimal:hover {
			background-color: #4195fc;
			border: 1px solid rgba(0,0,0,.1);
			color: rgb(255,255,255);
			cursor: pointer;
			text-shadow: 0 1px 1px rgba(0, 0, 0, 0.25);
		}

		.btn-minimal:active {
			box-shadow: 0 1px 1px rgba(0,0,0,0.15) inset;
			text-shadow: 0 -1px 1px rgba(0, 0, 0, 0.25);
		}

	 #loginBox {
		background-color: rgb(255,255,255);
   border: 1px solid rgb(75,0,130);
		border-radius: 4px;
		box-shadow: 0 1px 0 rgba(255,255,255,0.2) inset, 0 0 4px rgba(0,0,0,0.2);
		margin: 40px auto; /*aligns center*/
		padding: 24px;
		width: 500px;
	}

	/*FORM*/
	form.minimal label {
		display: block;
		margin: 6px 0;
	}

		form.minimal input[type="text"],
		form.minimal input[type="email"],
		form.minimal input[type="number"],
		form.minimal input[type="search"],
		form.minimal input[type="password"],
		form.minimal textarea {
			background-color: rgb(255,255,255);
			border: 1px solid rgb(75,0,130);
			border-radius: 2px;
			-webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.08);
			-moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.08);
			  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.08);
			display: block;
			font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, 'lucida grande', tahoma, verdana, arial, sans-serif;
			font-size: 14px;
			margin: 6px 0 12px 0;
			padding: 8px;
			text-shadow: 0 1px 1px rgba(255, 255, 255, 1);
			width: 90%;

			-webkit-transition: all 0.1s linear;
			-moz-transition: all 0.1s linear;
			-o-transition: all 0.1s linear;
			  transition: all 0.1s linear;
		}

		form.minimal input[type="text"]:focus,
		form.minimal input[type="email"]:focus,
		form.minimal input[type="number"]:focus,
		form.minimal input[type="search"]:focus,
		form.minimal input[type="password"]:focus,
		form.minimal textarea:focus,
		form.minimal select:focus {
   		 	border-color: #4195fc;
    		-webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 0 8px #4195fc;
			-moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 0 8px #4195fc;
			box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 0 8px #4195fc;
			color: rgb(0,0,0);
		}

			form.minimal input[type="text"]:invalid:focus,
			form.minimal input[type="email"]:invalid:focus,
			form.minimal input[type="number"]:invalid:focus,
			form.minimal input[type="search"]:invalid:focus,
			form.minimal input[type="password"]:invalid:focus,
			form.minimal textarea:invalid:focus,
			form.minimal select:invalid:focus {
				border-color: rgb(248,66,66);
				-webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 0 8px rgb(248,66,66);
				-moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 0 8px rgb(248,66,66);
				  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 0 8px rgb(248,66,66);
			}

p {
  color: rgba(0,0,0,.8)
  font-size: .8em;
  margin: 0 0 24px 0;
}
  </style>
  </body>
</html>

mysite/app/templates/app/match.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <title>Match</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="testbox">
      <form action="post">
          {% csrf_token %}
        {% if Matches %}
        <h1>Other people have also had a problematic experience with this person.</h1><br>
        {% else %}
        <h1>We haven't found any matches yet, but we can keep you posted.</h1><br>
        {% endif %}
        <p>
          If you choose to follow up, a UW confidential advocate will reach out to you to talk about
          your options, including connecting with the other user if they also choose to follow up.
          Confidential advocates are professionals who will provide you with information and guidance
          on deciding how to move forward, if you choose. You can find out more about campus safety
          advocates <a href="https://www.washington.edu/sexualassault/support/advocacy/">here</a>.<br>
        </p>

        <p>
          Be aware that the campus safety advocates will receive no information from our databases
          except your email address, with which to contact you, and the contact information of the
          other user, if they choose to follow up as well.
          We encourage you to follow up, because by getting in touch with a confidential advocate,
          you are not required to move forward with any action. Rather, it is an opportunity to learn
          about your options and other helpful resources.
        </p>
        <h4>Would you like to follow up?</h4>
        <select>
          <option value=""></option>
          <option value="">Yes</option>
          <option value="2">No</option>
        </select><br><br>
            <button type="submit" formaction="resourcesT">Submit</button>
      </form>
    </div>
  </body>
</html>

mysite/app/templates/app/nomatch.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <title>Match</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="testbox">
      <form action="/">
        <h1> Thank you for submitting.</h1>
        <h1>At this time, we do not have any other documented cases of issues with <br><br> the same perpetrator.</h1><br>
        <p>
          However, if another user submits a report about the same perpetrator, we will contact you
          to let you know. At that time, you will be given the option to follow up, in which case a
          campus safety advocate will reach out to you for support in learning about resources and
          options for moving forward, if you are interested.
        </p><br>
          <h3>Click the button below for additional resources and support:</h3><br>
              <button type="submit" formaction="resources.html">Resources</button>
      </form>
    </div>
  </body>
</html>

mysite/app/templates/app/question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Enter Information about the Event</title>
</head>
<body>

</body>
</html>

mysite/app/templates/app/resources.html
<!DOCTYPE html>
<html lang="en">
<title>SAVE</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<body>

<div class="w3-top">
  <div class="w3-bar w3-deep-purple w3-card w3-center-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-deep-purple" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/" class="w3-bar-item w3-button w3-padding-large w3-deep-purple">Home</a>
    <a href="/resources" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-white w3-hover-deep-purple">Resources</a>

  </div>

  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="/resources" class="w3-bar-item w3-button w3-padding-large">Resources</a>

  </div>
</div>

<div class="w3-row-padding w3-padding-64 w3-container">
    <div class="w3-twothird">

      {% if submitted %}
      <h1>Thank you for submitting your confidential report.</h1>
      {% endif %}

      <p class="txt"><b>Find more resources at the University of Washington: </b><br><br>
         <a href="https://www.washington.edu/sexualassault/" target="_blank">www.washington.edu/sexualassault</a>
      </p>
      <p class="txt">
        More resources:
            Seattle Police Department  <a href="https://www.seattle.gov/police/need-help/sexual-assault" target="_blank">
            Seattle.gov/police/need-help/sexual-assault:</a><br>
            Callisto, survivors to survivors:  <a href="https://www.projectcallisto.org" target="_blank">Projectcallisto.org</a><br>
            RAINN (Rape, Abuse & Incest National Network):  <a href="https://www.rainn.org/about-rainn" target="_blank">Rainn.org</a><br>
      </p>
    </div>

    <div class="w3-third w3-center">
      <p class="quote"><b>“You’re not a victim for sharing your story. You are a survivor setting the world on fire
        with your truth. You never know who needs your light, your warmth and raging courage.” - Alex Elle</b></p>
    </div>
</div>

  <header class="w3-container w3-deep-purple w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">Click Below to Start a Report</h1>
  <form>
    <button type="submit" formaction="confidentiality.html">Begin</button>
  </form>
  </header>
  <style>
  .quote{
    text-align: center;
    margin-top: 120px;
    margin-right: 50px;
    color: purple;

  }
  .txt{
    color: black;
    font-size: 14px;
    text-align: left;

  }
  .button {
  background-color: #DCDCDC;
  border: none;
  color: black;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin-bottom: 2px;
  }

  </style>
<script>
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

<SCRIPT LANGUAGE="JavaScript">
function isCheckFiring(form) {
    if (form.checkThis.checked) {
        alert("The box is checked.")
    } else {
        alert("The box is not checked at the moment.")
    }
}
</SCRIPT>
</body>
</html>